USE [CCPortal];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/*
    Refresh CCPortal.dbo.tblPORTALCards from CAPS.dbo.tblCAPSCard.

    Source:
        CAPS.dbo.tblCAPSCard

    Target:
        CCPortal.dbo.tblPORTALCards

    Notes:
    - tblCAPSCard.CardID is loaded into tblPORTALCards.tblCardID
    - tblPORTALCards.CardID remains an identity generated by CCPortal
    - portal-only columns are left NULL/default on refresh
*/

BEGIN TRY
    BEGIN TRANSACTION;

    DELETE FROM dbo.tblPORTALCards;

    INSERT INTO dbo.tblPORTALCards
    (
        tblCardID,
        EmployeeID,
        ApplicationID,
        CardType,
        CardTypeSub,
        Title,
        FirstName,
        MiddleName,
        Surname,
        Address1,
        Address2,
        Address3,
        Suburb,
        State,
        PostCode,
        CreditLimit,
        CreditLimitAmount,
        Status,
        Expiry,
        CardNumber,
        AccountNumber,
        HomePhone,
        WorkPhone,
        MobilePhone,
        TransactionLimit,
        ATMLimit,
        OTCLimit,
        Email,
        CMSUser,
        ProcessStatus,
        NameOnCard,
        DateLoaded,
        Notes,
        DefaultCompany,
        DefaultCostCentre,
        PMLoadStatus,
        PMLoadDate,
        ReportGroup,
        Relationship,
        ActivationFlag,
        PlasticID,
        FileDateTime,
        FileSeqNum,
        CardNumberShort,
        Companion,
        DateIssued,
        Active,
        CardID2,
        UpdatedBy,
        DateUpdated
    )
    SELECT
        src.CardID,
        src.EmployeeID,
        src.ApplicationID,
        src.CardType,
        src.CardTypeSub,
        src.Title,
        src.FirstName,
        src.MiddleName,
        src.Surname,
        src.Address1,
        src.Address2,
        src.Address3,
        src.Suburb,
        src.State,
        src.PostCode,
        src.CreditLimit,
        src.CreditLimitAmount,
        src.Status,
        src.Expiry,
        src.CardNumber,
        src.AccountNumber,
        src.HomePhone,
        src.WorkPhone,
        src.MobilePhone,
        src.TransactionLimit,
        src.ATMLimit,
        src.OTCLimit,
        src.Email,
        src.CMSUser,
        src.ProcessStatus,
        src.NameOnCard,
        src.DateLoaded,
        src.Notes,
        src.DefaultCompany,
        src.DefaultCostCentre,
        src.PMLoadStatus,
        src.PMLoadDate,
        src.ReportGroup,
        src.Relationship,
        src.ActivationFlag,
        src.PlasticID,
        src.FileDateTime,
        LEFT(src.FileSeqNum, 10),
        src.CardNumberShort,
        src.Companion,
        src.DateIssued,
        src.Active,
        src.CardID2,
        0,
        SYSUTCDATETIME()
    FROM [CAPS].[dbo].[tblCAPSCard] AS src;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
GO
