<?php
declare(strict_types=1);

namespace App\Shared;

final class PdfReport
{
    /**
     * Config:
     *  - title, filename, meta[], mode: 'table'|'sections'
     *  - When mode='table': columns[], rows[]
     *  - When mode='sections': sections[] = [ ['title'=>'', 'html'=>'...'], ... ]
     */
    public static function render(array $config): void
    {
        $esc = static fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');

        $title    = $config['title']    ?? 'Report';
        $filename = $config['filename'] ?? 'report.pdf';
        $meta     = $config['meta']     ?? [];
        $mode     = $config['mode']     ?? 'table';

        // ---- Build HTML (self-contained styles) ----
        ob_start();
        echo "<!doctype html><html><head><meta charset='utf-8'>";
        echo "<style>
/* Clean, neutral PDF styles — no Bootstrap */
body { font-family: \"Segoe UI\", Calibri, Helvetica, Arial, sans-serif; color:#1f2937; margin:0; padding:0; }
h1 { font-size:18px; font-weight:600; margin:0 0 10px; color:#0f172a; }
p.meta { font-size:10px; color:#6b7280; margin:0 0 12px; }
.pdf-main table { width:100%; border-collapse:collapse; font-size:10px; }
.pdf-main th, .pdf-main td { border:0.8pt solid #9aa0a6; padding:4px 6px; text-align:left; vertical-align:top; }
.pdf-main th { background:#f3f4f6; font-weight:600; color:#111827; }
.section { margin-bottom:18px; }
.section-title { font-size:14px; font-weight:600; color:#0f172a; margin:16px 0 8px; padding-bottom:3px; border-bottom:2px solid #d1d5db; }
.page-break { page-break-after:always; }
</style>";
        echo "</head><body><div class='pdf-main'>";

        echo "<h1>" . $esc($title) . "</h1>";

       

        if ($mode === 'table') {
            $columns = $config['columns'] ?? [];
            $rows    = $config['rows']    ?? [];

            echo "<table><thead><tr>";
            foreach ($columns as $c) {
                echo "<th>" . $esc($c['label']) . "</th>";
            }
            echo "</tr></thead><tbody>";

            foreach ($rows as $r) {
                echo "<tr>";
                foreach ($columns as $c) {
                    $val = $r[$c['key']] ?? '';
                    echo "<td>" . $esc($val) . "</td>";
                }
                echo "</tr>";
            }
            if (!$rows) {
                echo "<tr><td colspan='" . count($columns) . "'>No records.</td></tr>";
            }
            echo "</tbody></table>";

        } elseif ($mode === 'sections') {
            $sections = $config['sections'] ?? [];
            foreach ($sections as $i => $s) {
                echo "<div class='section'>";
                echo "<div class='section-title'>" . $esc($s['title'] ?? ('Section ' . ($i + 1))) . "</div>";
                echo $s['html'] ?? ''; // include tables/markup; they inherit .pdf-main rules
                echo "</div>";
                if ($i < count($sections) - 1) echo "<div class='page-break'></div>";
            }
        }

        echo "</div></body></html>";
        $html = ob_get_clean();

        // ---- Header / Footer (thin line only; never boxed) ----
        $tmpDir  = sys_get_temp_dir();
        $stamp   = date('Ymd_His') . '_' . substr(sha1(random_bytes(8)), 0, 6);
        $hdrPath = $tmpDir . "/cbms_hdr_$stamp.html";
        $ftrPath = $tmpDir . "/cbms_ftr_$stamp.html";

        $headerHtml = '<!doctype html><meta charset="utf-8">
<style>
body { margin:0; font:9px \"Segoe UI\", Arial, sans-serif; color:#444; }
table.bar { width:100%; border-collapse:collapse; }
table.bar { border-bottom:1px solid #9aa0a6; }
table.bar th, table.bar td { border:none !important; }
td { padding:2mm 8mm; } .right { text-align:right; }
</style>
<table class="bar"><tr>
  <td>' . $esc($title) . '</td>
  <td class="right">CBMSv2.1</td>
</tr></table>';

// In PdfReport::render(), before $footerHtml:
$genUser = htmlspecialchars((string) \App\Shared\SessionHelper::get('auth.username', 'system'), ENT_QUOTES, 'UTF-8');
$genDate = date('Y-m-d H:i');

$footerHtml = <<<HTML
<!doctype html><meta charset="utf-8">
<style>
  body { margin:0; font:9px "Segoe UI", Arial, sans-serif; color:#6b7280; }
  .bar { border-top:1px solid #d1d5db; width:100%; }
  td { padding:2mm 8mm; }
  .right { text-align:right; }
</style>
<script>
  function subst(){
    var qs = window.location.search.substring(1).split("&"), map={};
    for(var i=0;i<qs.length;i++){
      var p=qs[i].split("="); map[decodeURIComponent(p[0])] = decodeURIComponent(p[1]||"");
    }
    var set=function(cls,val){ var els=document.getElementsByClassName(cls);
      for(var j=0;j<els.length;j++) els[j].textContent=val;
    };
    set("page", map.page || "");
    set("topage", map.topage || "");
  }
</script>
<body onload="subst()">
  <table class="bar"><tr>
    <td>Generated by {$genUser} on {$genDate}</td>
    <td class="right">Page <span class="page"></span> of <span class="topage"></span></td>
  </tr></table>
</body>
HTML;




        file_put_contents($hdrPath, $headerHtml);
        file_put_contents($ftrPath, $footerHtml);

        try {
            $flags = [
                '--header-html', $hdrPath,
                '--footer-html', $ftrPath,
                '--margin-top','12mm',
                '--margin-bottom','12mm',
                '--dpi','96',
            ];

            $pdfPath = Pdf::fromHtml($html, $flags, 120);

            if (ob_get_length()) { @ob_end_clean(); }
            header('Content-Type: application/pdf');
            header('Content-Disposition: inline; filename="' . $filename . '"');
            header('Content-Length: ' . filesize($pdfPath));
            readfile($pdfPath);
        } finally {
            if (!empty($pdfPath) && is_file($pdfPath)) @unlink($pdfPath);
            if (is_file($hdrPath)) @unlink($hdrPath);
            if (is_file($ftrPath)) @unlink($ftrPath);
        }
        exit;
    }
}
